:toc: macro
toc::[]

== Testing devon4j SNAPSHOT releases

Whenever a story in devon4j is completed by merging a https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[PR],
our https://github.com/features/actions[github actions] will build a new SNAPSHOT release and on success deploy it to nexus on OSSRH.
You can therefore find the latest devonfw SNAPSHOT releases https://oss.sonatype.org/content/repositories/snapshots/com/devonfw/[here].

In order to test a SNAPSHOT release in your project e.g. to give feedback if a bugfix or feature is working as you expect, you can do the following:

1. Add the repository https://oss.sonatype.org/content/repositories/snapshots/[].
If you are using a recent https://github.com/devonfw/ide[devonfw-ide] simply edit the file `$DEVON_IDE_HOME/conf/.m2/settings.xml` and activate the `devonfw-snapshots` profile by changing `activeByDefault` to `true`.
All details can be found https://github.com/devonfw/ide-settings/blob/master/devon/conf/.m2/settings.xml#L60[here].

2. Edit your toplevel `pom.xml` file and change the `devon4j.version` to the most recent `SNAPSHOT` version. To figure out the latest SNAPSHOT version of devon4j, check the the https://github.com/devonfw/devon4j/blob/master/.mvn/maven.config[maven.config] or the https://github.com/devonfw/devon4j/blob/master/CHANGELOG.adoc[CHANGELOG].

3. Test your appliation and see if the latest SNAPSHOT release fixes your issues, does not break your app and works as expected.

4. Give us feedback. We love to hear your feedback:

* If and issue is not fixed as expected, comment the according issue on github.
* If something broke or does not work as expected, please file a https://github.com/devonfw/devon4j/issues/new/choose[new issue] and provide details (stacktrace, error log, etc.) but no confidentail data (passwords, customer details, etc.).
* If your test succeeded with the latest SNAPSHOT please also give confirming feedback to bug or feature tickets to let us know.

Thanks for your testing, support and help to make devonfw better!
