:toc: macro
toc::[]

== Component Facade
[NOTE]
Our recommended approach for implementing the logic layer is xref:guide-usecase.adoc[use-cases]

For each component of the application, the xref:guide-logic-layer.adoc[logic layer] defines a component facade.
This is an interface defining all business operations of the component.
It carries the name of the component (`«Component»`) and has an implementation named `«Component»Impl` (see xref:implementation[implementation]).

== API
The component facade interface defines the logic API of the component and has to be business oriented.
This means that all parameters and return types of all methods from this API have to be business xref:guide-transferobject.adoc[transfer-objects], xref:guide-datatype.adoc[datatypes] (`String`, `Integer`, `MyCustomerNumber`, etc.), or collections of these.
The API may also only access objects of other business components listed in the (transitive) dependencies of the xref:architecture.adoc#business-architecture[business-architecture].

Here is an example how such an API may look like:
[source,java]
----
public interface Bookingmanagement {

  BookingEto findBooking(Long id);

  BookingCto findBookingCto(Long id);

  Page<BookingEto> findBookingEtos(BookingSearchCriteriaTo criteria);

  void approveBooking(BookingEto booking);

}
----

== Implementation
The implementation of an interface from the xref:guide-logic-layer.adoc[logic layer] (a component facade or a xref:guide-usecase.adoc[use-case]) carries the name of that interface with the suffix `Impl` and is annotated with `@Named`.
An implementation typically needs access to the persistent data.
This is done by xref:guide-dependency-injection.adoc[injecting] the corresponding xref:guide-repository.adoc[repository] (or xref:guide-dao.adoc[DAO]).
According to xref:architecture.adoc#architecture-principles[data-sovereignty], only repositories of the same business component may be accessed directly.
For accessing data from other components the implementation has to use the corresponding API of the logic layer (the component facade). Further, it shall not expose persistent entities from the xref:guide-domain-layer.adoc[domain layer] and has to map them to xref:guide-transferobject.adoc[transfer objects] using the xref:guide-beanmapping.adoc[bean-mapper].

[source,java]
----

@Named
@Transactional
public class BookingmanagementImpl extends AbstractComponentFacade implements Bookingmanagement {

  @Inject
  private BookingRepository bookingRepository;

  @Override
  public BookingEto findBooking(Long id) {

    LOG.debug("Get Booking with id {} from database.", id);
    BookingEntity entity = this.bookingRepository.findOne(id);
    return getBeanMapper().map(entity, BookingEto.class));
  }
}
----

As you can see, xref:guide-jpa.adoc#entity[entities] (`BookingEntity`) are mapped to corresponding xref:guide-transferobject.adoc#eto[ETOs] (`BookingEto`).
Further details about this can be found in xref:guide-beanmapping.adoc[bean-mapping].
