= Changelog of devon4j

This file documents all notable changes to https://https://github.com/devonfw/devon4j[devon4j].

== 3.2.1

Bugfix release:

* https://github.com/devonfw/devon4j/issues/166[#166]: JUnit5 not working (in Eclipse)
* https://github.com/devonfw/devon4j/pull/170[#170]: show SQL from hibernate during development for debugging
* https://github.com/devonfw/devon4j/pull/168[#168]: fixes for JUnit5 to work properly in all environments

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.2.1/devon4j-doc-3.2.1.pdf[devon4j guide 3.2.1].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/10?closed=1[milestone devon4j 3.2.1].

== 3.2.0

The following changes have been incorporated in devon4j:

* https://github.com/devonfw/devon4j/pull/140[#140]: Completed full support from Java8 to Java11
* https://github.com/devonfw/devon4j/issues/96[#96]: Several security fixes
* https://github.com/devonfw/devon4j/pull/163[#163]: Upgrade to Spring Boot 2.1.9
* https://github.com/devonfw/devon4j/pull/163[#163]: Upgrade to Spring 5.1.8
* https://github.com/devonfw/devon4j/issues/130[#130]: Upgrade to JUnit 5 (requires migration via devonfw-ide)
* https://github.com/devonfw/devon4j/issues/150[#150]: Improved JPA support for IdRef
* https://github.com/devonfw/devon4j/issues/47[#47]: Improved auditing metadata support
* https://github.com/devonfw/devon4j/pull/140[#140]: Many improvements to documentation (added JDK guide, architecture-mapping, JMS, etc.)

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.2.0/devon4j-doc-3.2.0.pdf[devon4j guide 3.2.0].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/6?closed=1[milestone devon4j 3.2.0].

== 3.1.1

Bugfix release for security fixes:

* https://github.com/devonfw/devon4j/issues/115[#115]: Resolve CVEs identified for 3.1.0 release 
* https://github.com/devonfw/devon4j/issues/122[#122]: Update guava to version 28.0-jre
* https://github.com/devonfw/devon4j/issues/123[#123]: Update jacskon to 2.9.9.1  
* https://github.com/devonfw/devon4j/pull/131[#131]: Resolve CVEs identified 

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.1.1/devon4j-doc-3.1.1.pdf[devon4j guide 3.1.1].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/7?closed=1[milestone devon4j 3.1.1].

== 3.1.0

The following changes have been incorporated in devon4j:

* https://github.com/devonfw/devon4j/issues/16[#16]: Added Support for Java8 up to Java11
* https://github.com/devonfw/devon4j/pull/111[#111]: Upgrade to Spring Boot 2.1.6.
* https://github.com/devonfw/devon4j/pull/111[#111]: Upgrade to Spring 5.1.8
* https://github.com/devonfw/devon4j/issues/12[#12]: Upgrade to JPA 2.2
* https://github.com/devonfw/devon4j/issues/12[#12]: Upgrade to Hibernate 5.3
* https://github.com/devonfw/devon4j/issues/72[#72]: Upgrade to Dozer 6.4.1 (ATTENTION: Requires Migration, use devon-ide for automatic upgrade)
* https://github.com/devonfw/devon4j/pull/101[#101]: Many improvements to documentation (added JDK guide, architecture-mapping, JMS, etc.)
* https://github.com/devonfw/devon4j/issues/106[#106]: Completed support (JSON, Beanmapping) for pagination, IdRef, and java.time
* https://github.com/devonfw/devon4j/pull/32[#32]: Added MasterCto

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.1.1/devon4j-doc-3.1.1.pdf[devon4j guide 3.1.1].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/3?closed=1[milestone devon4j 3.1.0].

== 3.0.2

Bugfix release :

* https://github.com/devonfw/devon4j/issues/93[#93]: Update to latest spring-boot 2.0.x for bugfix release devon4j 3.0.x 

The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/5?closed=1[milestone devon4j 3.0.2].

== 3.0.1

Bugfix release :

* https://github.com/devonfw/devon4j/pull/48[#48]: Fixed NPE for uuid instance

The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/2?closed=1[milestone devon4j 3.0.1].

== 3.0.0

The following changes have been incorporated in devon4j:

* https://github.com/oasp/oasp4j/issues/674[#674]: Spring Boot 2.0.4 Integrated.[oasp4j]
* https://github.com/oasp/oasp4j/issues/626[#626]: Spring Data layer Integrated.[oasp4j]
* https://github.com/devonfw/devon4j/issues/14[#14]: Decouple mmm.util.*
* https://github.com/oasp/oasp4j/issues/648[648]: Removed depreciated restaurant sample.[oasp4j]
* https://github.com/oasp/oasp4j/issues/669[#669]: Updated Pagination support for Spring Data[oasp4j]
* https://github.com/oasp/oasp4j/pull/671[#671]: Add support for hana as dbType.

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.0.0/devon4j-doc-3.0.0.pdf[devon4j guide 3.0.0].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/1?closed=1[milestone devon4j 3.0.0].
and https://github.com/oasp/oasp4j/milestone/24?closed=1[milestone oasp4j 3.0.0]

Note : If you want to upgrade devon4j version in your project, please see https://github.com/devonfw/ide/blob/master/documentation/java.asciidoc#migrate
