-- *** BinaryObject (BLOBs) ***
CREATE COLUMN TABLE BinaryObject (
  id                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  modificationCounter INTEGER NOT NULL,
  content             BLOB,
  filesize            BIGINT NOT NULL,
  mimeType            VARCHAR(255),
  CONSTRAINT PK_BinaryObject_id PRIMARY KEY(ID)
);
