:toc:
toc::[]

= Decision Sheet for Choosing a Service Framework

We need to choose which framework(s) we are using to build services. For the devonfw we focus on a standard API if available. However, we also want to recommend an implementation to use. While projects would still be able to choose whatever they want, we want to suggest the best, most robust and established solution. This way projects do not have to worry about the decision and can rely on a production ready framework without getting into trouble. Also besides the standard the configuration of the implementation framework differs and we want to give instructions how to do this in the documentation and by our sample application. This is why in the end the implementation also matters. If a project has a customer demand to use something else then the project has to take care of this. We will always suggest and "support" ONE solution.

== REST Services
For REST services we rely on the JAX-RS standard (and NOT on spring-mvc with its proprietary annotations).
As JAX-RS implementation had Jersey (Reference-Implementation) and Apache CXF on the short-list. As it turned out, Jersey is build for HK2 and the spring integration is rather a quickfix. So we ran into bugs when we used it with spring. There are various issues open in the jersey tracker related to this. E.g. https://java.net/jira/browse/JERSEY-2112
For Apache CXF the spring container was first choice but container abstraction has been properly introduced by design so it can be used in JEE application servers. Everything works smooth in our sample application and we collected feedback from various projects doing JAX-RS based on CXF either with XML or JSON with success in production. 

Therefore we decided for Apache CXF here.

Update: We still get questions like "Why don't you use `resteasy` or `dropwizard`?"

To give a plain answer here you can see the stacktrace of a productive system using `resteasy` and failing to invoke a service:
```
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:200)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:171)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:480)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:169)
```

This is an error you get when using `devon4j` with CXF:
```
net.sf.mmm.util.exception.api.ServiceInvocationFailedException: 404: While invoking the service com.devonfw.test.app.myexample.service.api.rest.MyExampleRestService#greet[http://localhost:49468/app/services-404/rest/my-example/v1/greet/John%20Doe] the following error occurred: Not Found. Probably the service is temporary unavailable. Please try again later. If the problem persists contact your system administrator.
4fb68fd0-a962-46ab-8655-99cb9e43c9ca
	at com.devonfw.module.service.common.impl.client.ServiceClientErrorFactoryImpl.create(ServiceClientErrorFactoryImpl.java:30)
	at com.devonfw.module.service.common.base.client.AbstractServiceClientErrorFactory.createException(AbstractServiceClientErrorFactory.java:83)
	at com.devonfw.module.service.common.base.client.AbstractServiceClientErrorFactory.unmarshall(AbstractServiceClientErrorFactory.java:65)
	at com.devonfw.module.cxf.common.impl.client.rest.RestServiceExceptionMapper.fromResponse(RestServiceExceptionMapper.java:59)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:422)
```
On success you will instead get such log message:
```
Invoking service com.devonfw.test.app.myexample.service.api.rest.MyExampleRestService#greet[http://localhost:50504/app/services/rest] took PT0.220281558S (220281558ns) and succeded with status 200.
```

== WebServices
For WebServices we rely on the JAX-WS standard. On our short list we have https://metro.java.net[Metro2] and http://cxf.apache.org[Apache CXF]. Here a collection of facts and considerations:

.Decision for JAX-WS implementation
[cols="asciidoc",options="header",grid="cols"]
|=======================
|        |*Metro2*|*Apache CXF*
|*Pro*   |
- reference implementation +
- proven in many projects +
- standard in RF
|
- supports both JAX-WS and JAX-RS therefore consistent configuration, single integration into servlet-container and spring +
- proven in a lot of projects +
- already chosen by devonfw for JAX-RS (so we already have a JAX-WS implementation on board).
|*Contra*|
- We expect trouble if use the planned URL path scheme +<app>/services/(rest\|ws)/...+ as CXF and Metro2 would both occupy +services/*+ +
- ugly endorsed trouble and small spring-integration issues with WSDL/XSD link resolution (input from Martin Girschik)
|
- IMHO currently used in less projects than metro2 so less existing experience +
|=======================

See also
http://predic8.de/axis2-cxf-jax-ws-vergleich.htm
We also had an evaluation at CSD research on CXF vs. Axis2. vs. Metro that suggested CXF.

BTW: Axis(2) is definitely out of discussion for devonfw.
