:toc: macro
toc::[]

= Configuration

An application needs to be configurable in order to allow internal setup (like CDI) but also to allow externalized configuration of a deployed package (e.g. integration into runtime environment). Using http://projects.spring.io/spring-boot/[Spring Boot] (must read: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot[Spring Boot reference]) we rely on a comprehensive configuration approach following a "convention over configuration" pattern. This guide adds on to this by detailed instructions and best-practices how to deal with configurations.

In general we distinguish the following kinds of configuration that are explained in the following sections:

* xref:internal-application-configuration[Internal Application configuration] maintained by developers
* xref:externalized-environment-configuration[Externalized Environment configuration] maintained by operators
* xref:business-configuration[Externalized Business configuration] maintained by business administrators

== Internal Application Configuration
The application configuration contains all internal settings and wirings of the application (bean wiring, database mappings, etc.) and is maintained by the application developers at development time. There usually is a main configuration registered with main Spring Boot App, but differing configurations to support automated test of the application can be defined using profiles (not detailed in this guide).

=== Spring Boot Application

The devonfw recommends using http://projects.spring.io/spring-boot/[spring-boot] to build web applications.
For a complete documentation see the http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/[Spring Boot Reference Guide].

With spring-boot you provide a simple _main class_ (also called starter class) like this:
//Using new SpringBootApp now
com.devonfw.mtsj.application
[source, java]
----
@SpringBootApplication(exclude = { EndpointAutoConfiguration.class })
@EntityScan(basePackages = { "com.devonfw.mtsj.application" }, basePackageClasses = { AdvancedRevisionEntity.class })
@EnableGlobalMethodSecurity(jsr250Enabled = true)
@ComponentScan(basePackages = { "com.devonfw.mtsj.application.general", "com.devonfw.mtsj.application" })
public class SpringBootApp {

  /**
   * Entry point for spring-boot based app
   *
   * @param args - arguments
   */
  public static void main(String[] args) {

    SpringApplication.run(SpringBootApp.class, args);
  }
}
----

In an devonfw application this main class is always located in the `<basepackage>` of the application package namespace (see link:coding-conventions.asciidoc#packages[package-conventions]). This is because a spring boot application will automatically do a classpath scan for components (spring-beans) and entities in the package where the application main class is located including all sub-packages. You can use the `@ComponentScan` and `@EntityScan` annotations to customize this behaviour.

If you want to map spring configuration properties into your custom code please see link:guide-configuration-mapping.asciidoc[configuration mapping].

=== Standard beans configuration

For basic bean configuration we rely on spring boot using mainly configuration classes and only occasionally XML configuration files. Some key principle to understand Spring Boot auto-configuration features:

* Spring Boot auto-configuration attempts to automatically configure your Spring application based on the jar dependencies and annotated components found in your source code.
* Auto-configuration is non-invasive, at any point you can start to define your own configuration to replace specific parts of the auto-configuration by redefining your identically named bean (see also `exclude` attribute of `@SpringBootApplication` in example code above).

Beans are configured via annotations in your java code (see link:guide-dependency-injection.asciidoc[dependency-injection]).

For technical configuration you will typically write additional spring config classes annotated with `@Configuration` that provide bean implementations via methods annotated with `@Bean`. See http://docs.spring.io/spring-javaconfig/docs/1.0.0.M4/reference/html/ch02s02.html[spring @Bean documentation] for further details. Like in XML you can also use `@Import` to make a `@Configuration` class include other configurations.

More specific configuration files (as required) reside in an adequately named subfolder of:

`src/main/resources/app`

=== BeanMapper Configuration
In case you are still using dozer, you will find further details in link:guide-beanmapping.asciidoc#bean-mapper-configuration[bean-mapper configuration].

=== Security configuration
The abstract base class `BaseWebSecurityConfig` should be extended to configure web application security thoroughly.
A basic and secure configuration is provided which can be overridden or extended by subclasses.
Subclasses must use the `@Profile` annotation to further discriminate between beans used in production and testing scenarios. See the following example:

.How to extend `BaseWebSecurityConfig` for Production and Test
[source,java]
----
@Configuration
@EnableWebSecurity
@Profile(SpringProfileConstants.JUNIT)
public class TestWebSecurityConfig extends BaseWebSecurityConfig {...}

@Configuration
@EnableWebSecurity
@Profile(SpringProfileConstants.NOT_JUNIT)
public class WebSecurityConfig extends BaseWebSecurityConfig {...}
----

See https://github.com/devonfw/my-thai-star/blob/develop/java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/config/WebSecurityConfig.java[WebSecurityConfig].


=== WebSocket configuration
A websocket endpoint is configured within the business package as a Spring configuration class. The annotation `@EnableWebSocketMessageBroker` makes Spring Boot registering this endpoint.
//Changed path due to non existent configuration in the example project
[source, java]
----
package your.path.to.the.websocket.config;
...
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractWebSocketMessageBrokerConfigurer {
...
----

=== Database Configuration

To choose database of your choice , set `spring.profiles.active=XXX` in `src/main/resources/config/application.properties`. Also, one has to set all the active spring profiles in this `application.properties` and not in any of the other `application.properties`.

== Externalized Configuration

Externalized configuration is a configuration that is provided separately to a deployment package and can be maintained undisturbed by re-deployments.

=== Environment Configuration

The environment configuration contains configuration parameters (typically port numbers, host names, passwords, logins, timeouts, certificates, etc.) specific for the different environments. These are under the control of the operators responsible for the application.

The environment configuration is maintained in `application.properties` files, defining various properties (see https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[common application properties] for a list of properties defined by the spring framework).
These properties are explained in the corresponding configuration sections of the guides for each topic:

* link:guide-jpa.asciidoc#database-system-and-access[persistence configuration]
* link:guide-service-layer.asciidoc#jax-rs-configuration[service configuration]
* link:guide-logging.asciidoc#configuration[logging guide]

For a general understanding how spring-boot is loading and boostrapping your `application.properties` see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[spring-boot external configuration].
The following properties files are used in every devonfw application:

* `src/main/resources/application.properties` providing a default configuration - bundled and deployed with the application package. It further acts as a template to derive a tailored minimal environment-specific configuration.
* `src/main/resources/config/application.properties` providing additional properties only used at development time (for all local deployment scenarios). This property file is excluded from all packaging.
* `src/test/resources/config/application.properties` providing additional properties only used for testing (JUnits based on link:guide-testing.asciidoc[spring test]).

For other environments where the software gets deployed such as `test`, `acceptance` and `production` you need to provide a tailored copy of `application.properties`. The location depends on the deployment strategy:

* standalone run-able Spring Boot App using embedded tomcat: `config/application.properties` under the installation directory of the spring boot application.
* dedicated tomcat (one tomcat per app): `$CATALINA_BASE/lib/config/application.properties`
* tomcat serving a number of apps (requires expanding the wars): `$CATALINA_BASE/webapps/<app>/WEB-INF/classes/config`

In this `application.properties` you only define the minimum properties that are environment specific and inherit everything else from the bundled `src/main/resources/application.properties`. In any case, make very sure that the classloader will find the file.

Make sure your properties are thoroughly documented by providing a comment to each property. This inline documentation is most valuable for your operating department.

=== Business Configuration
Often applications do not need business configuration. In case they do it should typically be editable by administrators via the GUI. The business configuration values should therefore be stored in the database in key/value pairs.

Therefore we suggest to create a dedicated table with (at least) the following columns:

* ID
* Property name
* Property type (Boolean, Integer, String)
* Property value
* Description

According to the entries in this table, an administrative GUI may show a generic form to modify business configuration. Boolean values should be shown as checkboxes, integer and string values as text fields. The values should be validated according to their type so an error is raised if you try to save a string in an integer property for example.

We recommend the following base layout for the hierarchical business configuration:

`component.[subcomponent].[subcomponent].propertyname`

== Security
Often you need to have passwords (for databases, third-party services, etc.) as part of your configuration. These are typically environment specific (see above). However, with DevOps and continuous-deployment you might be tempted to commit such configurations into your version-control (e.g. `git`). Doing that with plain text passwords is a severe problem especially for production systems. Never do that! Instead we offer some suggestions how to deal with sensible configurations:

=== Password Encryption
Let us have a look how to encrypt password using `jasypt-springboot-starter` and `jasypt-springboot`.

You can also have a look at their page link:http://www.jasypt.org/index.html[Jasypt].

==== How to Use Jasypt-SpringBoot-Starter
The first step would be to add the starter dependency to our `pom.xml` file.

[source,xml]
----
<dependency>
    <groupId>com.github.ulisesbocchio</groupId>
    <artifactId>jasypt-spring-boot-starter</artifactId>
    <version>2.0.0</version>
</dependency>
----

Please check the latest version link:https://mvnrepository.com/artifact/com.github.ulisesbocchio/jasypt-spring-boot-starter[here] .

This will smoothly integrate http://jasypt.org/[jasypt] into your https://projects.spring.io/spring-boot/[spring-boot] application. Read this https://wiki.jasig.org/display/CASUM/HOWTO+Use+Jasypt+to+encrypt+passwords+in+configuration+files[HOWTO] to learn how to encrypt and decrypt passwords using jasypt. Here is a simple example output of an encrypted password (of course you have to use strong passwords instead of `secret` and `postgres` - this is only an example):

[source, bash]
----
ARGUMENTS

input: postgres
password: secret

OUTPUT

jd5ZREpBqxuN9ok0IhnXabgw7V3EoG2p
----

Let's now encrypt the text`Password@1` with secret key`password`  and add it to the `encrypted.properties`:
[source,properties]
----
encrypted.property=ENC(uTSqb9grs1+vUv3iN8lItC0kl65lMG+8)
----

And let's define a configuration class `ConfigForJasyptStarter` – to specify the `encrypted.properties` file as a PropertySource :

[source,java]
----
@Configuration
@PropertySource("encrypted.properties")
public class AppConfigForJasyptStarter {
}
----

Let's create service bean class to retrieve the values from `encrypted.properties` file.
The decrypted value can be retrieved using the `@Value` annotation or the getProperty() method of `Environment` class. See below example:

[source,java]
----
@Service
public class PropertyMapperJasyptStarter {

    @Value("${encrypted.property}")
    private String property;

    public String getProperty() {
        return property;
    }

    public String getPasswordUsingEnvironment(Environment environment) {
        return environment.getProperty("encrypted.property");
    }
}
----

Using the above service class and setting the secret key which we used for encryption, we can easily retrieve the decrypted password and use in our application.

==== How to use Jasypt-SpringBoot
For projects not using `@SpringBootApplication` or `@EnableAutoConfiguration`, we can use the jasypt-spring-boot dependency directly

[source,xml]
----
<dependency>
    <groupId>com.github.ulisesbocchio</groupId>
    <artifactId>jasypt-spring-boot</artifactId>
    <version>2.0.0</version>
</dependency>
----

Please check for latest version link:https://mvnrepository.com/artifact/com.github.ulisesbocchio/jasypt-spring-boot[here] .

let's encrypt the text `Password@2` with secret key `password` and add it to the `encrypted.properties`.

[source,properties]
----
encrypted.property=ENC(dQWokHUXXFe+OqXRZYWu22BpXoRZ0Drt)
----

New configuration class is required for `Jasypt-springboot` dependency and we need to add the annotation `@EncryptablePropertySource` at the class level.

Below is an example,

[source,java]
----
@Configuration
@EncryptablePropertySource("encrypted.properties")
public class AppJasyptConfig {
}
----

And a service class to map the property in encrypted.properties.
[source,java]
----
@Service
public class PropertyMapperJasypt {

    @Value("${encrypted.property}")
    private String property;

    public String getProperty() {
        return property;
    }
}
----
Using the above service class and setting the secret key which we used for encryption, we can easily retrieve the encrypted.property.

== How to use custom Jasypt Encryptor

The encryptors mentioned above has their own configuration. We can also define our own Jasypt encryptor and use it on our application.

See below example,

[source,java]
----
@Bean(name = "encryptorBean")
public StringEncryptor stringEncryptor() {
    PooledPBEStringEncryptor encryptor = new PooledPBEStringEncryptor();
    SimpleStringPBEConfig config = new SimpleStringPBEConfig();
    config.setPassword("password");
    config.setAlgorithm("PBEWithMD5AndDES");
    config.setKeyObtentionIterations("1000");
    config.setPoolSize("1");
    config.setProviderName("SunJCE");
    config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
    config.setStringOutputType("base64");
    encryptor.setConfig(config);
    return encryptor;
}
----
We can modify all the properties for the SimpleStringPBEConfig. We need to add a property `jasypt.encryptor.bean` to our `application.properties`, so that Spring Boot knows which Custom Encryptor it should use.

For example, we add the custom text “Password@3” encrypted with secret key “password” in the application.properties,

[source,properties]
----
jasypt.encryptor.bean=encryptorBean
encrypted.property=ENC(askygdq8PHapYFnlX6WsTwZZOxWInq+i)
----

Once we set it, we can easily get the encrypted.property from the Spring's Environment

To test that below is an example,
[source,java]
----
@Test
public void whenConfiguredExcryptorUsed_ReturnCustomEncryptor() {
    Environment environment = appCtx.getBean(Environment.class);

    assertEquals(
      "Password@3",
      environment.getProperty("encrypted.property"));
}
----

As system properties given on the command-line are visible in the process list, we recommend to use an `config/application.yml` file only for this purpose (as we recommended to use `application.properties` for regular configs).

[source,properties]
----
jasypt:
    encryptor:
        password: password@1
----

To prevent jasypt to throw an exception in dev or test scenarios simply put this in your local config (`src/main/config/application.properties` and same for `test`, see above for details):
```
jasypt.encryptor.password=none
```

==== Is this Security by Obscurity?

* Yes, from the point of view to protect the passwords on the target environment this is nothing but security by obscurity. If an attacker somehow got full access to the machine this will only cause him to spend some more time.
* No, if someone only gets the configuration file. So all your developers might have access to the version-control where the config is stored. Others might have access to the software releases that include this configs. But without the master-password that should only be known to specific operators none else can decrypt the password (except with brute-force what will take a very long time, see jasypt for details).
