:toc: macro
toc::[]

= Caching
//Maybe finish the guide?
Caching is a technical approach to improve performance. While it may appear easy on the first sight it is an advanced topic. In general, try to use caching only when required for performance reasons. If you come to the point that you need caching first think about:

* What to cache? + 
Be sure about what you want to cache. Is it static data? How often will it change? What will happen if the data changes but due to caching you might receive "old" values? Can this be tolerated? For how long? This is not a technical question but a business requirement.
* Where to cache? +
Will you cache data on client or server? Where exactly?
* How to cache? +
Is a local cache sufficient or do you need a shared cache?

== Local Cache

== Shared Cache

=== Distributed Cache

== Products

* http://ehcache.org/
* http://hazelcast.org/
* http://terracotta.org/
* http://memcached.org/

== Caching of Web-Resources

* http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/
* http://en.wikipedia.org/wiki/Web_cache#Cache_control
* http://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Avoiding_caching