:toc: macro
toc::[]

= Auditing

For database auditing we use http://envers.jboss.org/[hibernate envers]. If you want to use auditing ensure you have the following dependency in your +pom.xml+:
[source,xml]
----
<dependency>
  <groupId>com.devonfw.java.modules</groupId>
  <artifactId>devon4j-jpa-envers</artifactId>
</dependency>
----

Make sure that entity manager also scans the package from the +devon4j-jpa[-envers]+ module in order to work properly.
[source,java]
----
@EntityScan(basePackages = { "«my.base.package»" }, basePackageClasses = { AdvancedRevisionEntity.class })
...
public class SpringBootApp {
  ...
}
----

Now let your DAO implementation extend from +AbstractRevisionedDao+ instead of +AbstractDao+ and your DAO interface extend from +[Application]RevisionedDao+ instead of +[Application]Dao+.

The DAO now has a method +getRevisionHistory(entity)+ available to get a list of revisions for a given entity and a method +load(id, revision)+ to load a specific revision of an entity with the given ID.
//Auditing is not used anymore
To enable auditing for a entity simply place the +@Audited+ annotation to your entity and all entity classes it extends from.
[source,java]
----
@Entity(name = "Drink")
@Audited
public class DrinkEntity extends ProductEntity implements Drink {
...
----

When auditing is enabled for an entity an additional database table is used to store all changes to the entity table and a corresponding revision number. This table is called +<ENTITY_NAME>_AUD+ per default. Another table called +REVINFO+ is used to store all revisions. Make sure that these tables are available. They can be generated by hibernate with the following property (only for development environments).
[source, properties]
----
  database.hibernate.hbm2ddl.auto=create
----

Another possibility is to put them in your link:guide-database-migration.asciidoc[database migration] scripts like so.
[source, sql]
----
CREATE CACHED TABLE PUBLIC.REVINFO(
  id BIGINT NOT NULL generated by default as identity (start with 1),
  timestamp BIGINT NOT NULL,
  user VARCHAR(255)
);
...
CREATE CACHED TABLE PUBLIC.<TABLE_NAME>_AUD(
    <ALL_TABLE_ATTRIBUTES>,
    revtype TINYINT,
    rev BIGINT NOT NULL
);
----