= devonfw for Java (devon4j)

Welcome to the Java edition of devonfw. devon4j is documented by a platform guide (see the side-bar of this wiki) to be used in your projects.

You will find the latest stable versions of documents generated from this wiki here:

* https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/3.1.0/devon4j-doc-3.1.0.pdf[stable devonfw devon4j guide as PDF].
If you want to search the wiki you might want to try https://github.com/linyows/github-wiki-search[github-wiki-search].

== For contributors
Contributors who like to contribute to the platform devonfw, please find menu-section devonfw Development on the right. Please read link:devonfw-ide-setup.asciidoc[IDE setup] and link:devonfw-code-contribution.asciidoc[Contribute code to devonfw] to get started. If you want to contribute to the devonfw-documentation (this wiki) please read the very important notes on link:devonfw-documentation.asciidoc[Maintain devonfw documentation] first.

Contributions and improvements to devonfw are very welcome. However, you should be aware of the following aspects:

* Your contributions will become part of devon4j documentation and get licensed under creative commons (see footer).
