:toc: macro
toc::[]

= Quarkus

https://quarkus.io[Quarkus] is a Java framework for building cloud-native apps.
It is fully supported by https://devonfw.com[devonfw] as an option and alternative to link:spring.asciidoc[spring].
Additional things like extensions will be available on the  https://github.com/devonfw/devon4quarkus[devon4quarkus] GitHub repository.

== Pros

Quarkus offers the following benefits:

* *fast turn-around cycles for developers* +
Save changes in your Java code and immediately test the results without restarting or waiting
* *faster start-up and less memory footprint* +
When building your app as link:quarkus/guide-native-image.asciidoc[native-images] via https://www.graalvm.org/[GraalVM] it gets highly optimized. As a result it starts up lightning fast and consumes much less memory. This is a great advantage for cloud deployment as well as for sustainability. You can find a performance comparison between Spring and Quarkus link:performance-comparision-spring-quarkus.asciidoc[here].
* *clean and lean*
As quarkus was born as cloud-native framework it is very light-weigth and does not carry much history and legacy.

== Cons

Quarkus has the following drawbacks:

* *less flexible* +
Quarkus is less flexible compared to link:spring.asciidoc[spring] or in other words it is more biased and coupled to specific implementations. However, the implementations just work and you have less things to choose and worry about. However, in case you want to integrate a specific or custom library you may hit limitations or lose support for link:quarkus/guide-native-image.asciidoc[native-images] especially when that library is based on reflection. Therefore, check your requirements and technology stack early on when making your choice.
* *less established* +
Since quarkus was born in 2019 it is modern but also less established. It will be easier to get developers for link:spring.asciidoc[spring] but we already consider quarkus mature and established enought for building production ready apps.