name: github actions for devon4j wiki
env:
  ORG: "devonfw"
  REPO_SOURCE: "devon4j"
  REPO_DEST: "devon4j.wiki"
  REPO_CONSOLIDATE: "devonfw-guide"
  GH_REPO_SOURCE: "github.com/${ORG}/${REPO_SOURCE}.git"
  GH_REPO_DEST:  "github.com/${ORG}/${REPO_DEST}.git"
  GH_REPO_CONSOLIDATE: "github.com/${ORG}/${REPO_CONSOLIDATE}.git" 
  BUILD_USER: ${{ secrets.BUILD_USER }}
  BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
  BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-wiki:
     if: ${{github.repository == 'devonfw/devon4j'}}
     runs-on: ubuntu-latest
     steps:
       - name: Documentation
         run: |
           git clone https://github.com/${ORG}/${REPO_SOURCE}.git ${REPO_SOURCE}
           git clone https://github.com/${ORG}/${REPO_DEST}.git ${REPO_DEST}
           git clone https://github.com/${ORG}/${REPO_CONSOLIDATE}.git ${REPO_CONSOLIDATE}
       - name: Copy docs and consolidate links
         run: |
           cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
           cd ${REPO_DEST}
           grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
           echo ">"
           git diff-index --quiet HEAD & git status -s
           echo "<"
           git status
           echo ">"
           git diff-index --quiet HEAD & git status -s
           echo "<"
           echo "TO_BE_CANCELLED=$(if [[ $(git diff-index --quiet HEAD & git status -s) ]]; then echo "false"; else echo "true"; fi)" >> $GITHUB_ENV
           echo "$TO_BE_CANCELLED"
       - name: setup git user
         if: ${{ env.TO_BE_CANCELLED == 'false' }}
         run: |
           git config --global user.email ${BUILD_USER_EMAIL}
           git config --global user.name ${BUILD_USER}
       - name: Sync Wiki
         if: ${{ env.TO_BE_CANCELLED == 'false' }}
         run: |
           cd ${REPO_DEST}
           git status
           git add .
           git commit -m "${REPO_SOURCE} documentation | GitHub Actions $GITHUB_WORKFLOW $GITHUB_RUN_NUMBER"
           git remote add origin-wiki "https://${BUILD_USER}:${BUILD_USER_PASSWD}@github.com/${ORG}/${REPO_DEST}.git"
           git push origin-wiki master
       - name: Sync devonfw guide
         if: ${{ env.TO_BE_CANCELLED == 'false' }}
         run: |
           cd ${REPO_CONSOLIDATE}
           if [ ! -d ${REPO_DEST} ]; then git submodule add https://github.com/${ORG}/${REPO_DEST}.git; fi;
           git submodule init
           git submodule update --recursive --remote
           cd ${REPO_DEST}
           git checkout master
           git pull
           cd ..
           git add .
           git commit -m "${REPO_SOURCE} documentation | GitHub Actions $GITHUB_WORKFLOW $GITHUB_RUN_NUMBER"
           git remote add origin-wiki "https://${BUILD_USER}:${BUILD_USER_PASSWD}@github.com/${ORG}/${REPO_CONSOLIDATE}.git"
           git push origin-wiki master
